spring:
    application:
        name: user
    liquibase:
        drop-first: true
        enabled: true
        change-log: classpath:/db/changelog/db.changelog-master.yaml
        default-schema: USR
    datasource:
        url: jdbc:postgresql://localhost:5432/topay-db
        name: topay-db
        username: postgres
        password: admin
        driver-class-name: org.postgresql.Driver
    jpa:
        show-sql: true
        properties:
            hibernate:
                format_sql: true
    security:
        oauth2:
            resourceserver:
                opaquetoken:
                    introspection-uri: http://localhost:8081/oauth/check_token
                    client-id: users
                    client-secret: users

